//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los cambios en este archivo podrían causar un comportamiento incorrecto
//     y se perderán si se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEditor.Controls
{
    public partial class OnlyOfficeEditor
    {
        // El control no contiene controles de servidor (runat="server")
        // por lo que el designer queda vacío.
    }
}
